name: dawakhaana
description: DUHacks 4.0 Instant Medicine Delivery Application project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' # Using the higher SDK constraint for compatibility

dependencies:
  flutter:
    sdk: flutter

  # razorpay integration
  razorpay_flutter: ^1.3.7

  # UI and Icons
  cupertino_icons: ^1.0.8 # Using the latest version

  # Firebase Dependencies
  firebase_core: ^3.12.0 # Using the latest stable version
  firebase_auth: ^5.5.0 # Using the latest stable version
  cloud_firestore: ^5.6.4 # Added from the first version

  # Geolocation
  geolocator: ^13.0.2 # Using the latest version

  # Google Sign-In
  google_sign_in: ^6.2.2 # Using the latest version

  # Local Storage
  shared_preferences: ^2.5.2 # Using the latest version

  # State Management
  provider: ^6.1.2 # Added from the second version

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0 # Using the latest version for better linting support

flutter:
  assets:
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/slide4.png
    - assets/images/slide5.png
    - assets/images/google_logo.png
    - assets/images/profile_placeholder.jpeg
    - assets/images/paracetamol.jpg
    - assets/images/ibuprofen.webp
    - assets/images/dolo.webp
    - assets/images/combiflam.jpg
    - assets/images/aspirin.webp
    - assets/images/naproxen.jpeg
    - assets/images/voveran.jpg
    - assets/images/crocin.jpg
    - assets/images/disprin.webp
    - assets/images/flexon.jpeg
    - assets/images/amoxicillin.webp
    - assets/images/azithromycin.jpg
    - assets/images/ciprofloxacin.jpeg
    - assets/images/doxycycline.jpg
    - assets/images/cephalexin.jpeg
    - assets/images/metronidazole.webp
    - assets/images/levofloxacin.jpeg
    - assets/images/clindamycin.jpeg
    - assets/images/erythromycin.webp
    - assets/images/tetracycline.jpg
    - assets/images/vitamin_c.jpg
    - assets/images/vitamin_d3.webp
    - assets/images/vitamin_b_complex.jpg
    - assets/images/vitamin_e.jpg
    - assets/images/multivitamin.webp
    - assets/images/vitamin_a.webp
    - assets/images/vitamin_k2.webp
    - assets/images/vitamin_b12.jpg
    - assets/images/vitamin_b6.webp
    - assets/images/vitamin_b1.jpeg
    - assets/images/benadryl.webp
    - assets/images/honitus.jpg
    - assets/images/corex_dx.jpg
    - assets/images/cheston.jpg
    - assets/images/torex.jpg
    - assets/images/ascoril.jpg
    - assets/images/grilinctus.jpg
    - assets/images/kofol.jpg
    - assets/images/alex.webp
    - assets/images/vicks.jpg
    - assets/images/durex_extra_thin.jpg
    - assets/images/durex_mutual_climax.jpg
    - assets/images/durex_pleasuremax.jpeg
    - assets/images/durex_invisible.jpg
    - assets/images/manforce_strawberry.webp
    - assets/images/manforce_chocolate.jpg
    - assets/images/kamasutra_ribbed.jpg
    - assets/images/kamasutra_dotted.webp
    - assets/images/durex_play_massage.jpg
    - assets/images/durex_play_tingling.jpg
    - assets/images/durex_play_warming.webp
    - assets/images/kamasutra_water_based.webp
    - assets/images/kamasutra_strawberry.jpg
    - assets/images/kamasutra_chocolate.webp
    - assets/images/ky_jelly.jpg
    - assets/images/id_glide.jpeg
    - assets/images/shilajit.webp
    - assets/images/ashwagandha.webp
    - assets/images/safed_musli.webp
    - assets/images/kaunch_beej.webp
    - assets/images/shatavari.jpg
    - assets/images/gokshura.webp
    - assets/images/vidari_kand.jpeg
    - assets/images/safed_musli_gold.jpg
    - assets/images/sexual_wellness_kit.webp
    - assets/images/intimacy_kit.jpeg
    - assets/images/couples_kit.jpg
    - assets/images/herbal_vitality_kit.jpg
    - assets/images/ayurvedic_kit.webp
    - assets/images/stress_relief_kit.webp
    - assets/images/energy_boost_kit.webp
    - assets/images/relaxation_kit.jpeg
    - assets/images/whey_gold_standard.webp
    - assets/images/muscleblaze_whey.webp
    - assets/images/optimum_nutrition.webp
    - assets/images/dymatize_iso100.jpg
    - assets/images/myprotein_whey.jpg
    - assets/images/bsn_syntha6.webp
    - assets/images/muscletech_nitrotech.webp
    - assets/images/gnc_pro_performance.jpg
    - assets/images/centrum.jpg
    - assets/images/one_a_day.webp
    - assets/images/nature_made.jpg
    - assets/images/gnc_mega_men.jpg
    - assets/images/kirkland.jpg
    - assets/images/rainbow_light.jpeg
    - assets/images/nordic_naturals.jpg
    - assets/images/nature_made_fish_oil.jpg
    - assets/images/carlson_omega3.jpeg
    - assets/images/garden_of_life_omega3.jpg
    - assets/images/now_foods_omega3.jpeg
    - assets/images/barleans_omega_swirl.jpg
    - assets/images/ashwagandha_capsules.jpg
    - assets/images/turmeric_curcumin.jpeg
    - assets/images/moringa_powder.jpg
    - assets/images/ginseng_extract.jpg
    - assets/images/aloe_vera_gel.webp

  uses-material-design: true